# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Show.destroy_all
Show.create(name: "City Hunter", description: "Decades ago, an elite team of South Korean security officers carried out a covert mission in North Korea to kill the top officials responsible for an attack on the South Korean president. But when the successful team returned to the submarine to take them back to South Korea, a sniper shot all the officers to eliminate all traces of the mission from the outside world. Officer Park Moo Yul (Park Shin Yen) sacrificed his own life to save his best friend, Lee Jin Pyo (Kim Sang Joong), who is the only survivor of the mission known as “Clean Sweep.” To fulfill a promise to his best friend, Jin Pyo kidnaps Moo Yul’s son, Lee Yoon Sung (Lee Min Ho), and raises him in a remote area of Thailand to become an elite combat soldier while patiently plotting to seek revenge on the “Council of Five” Korean government officials who planned operation Clean Sweep. After earning a Ph.D. at the Massachusetts Institute of Technology in the United States, the highly trained Yoon Sung returns to South Korea to work at the Blue House’s National Communication Network Team and carry out Jin Pyo’s plan for revenge under the codename “City Hunter.” Yoon Sung is aided in his quest by Bae Man Duk (Kim Sang Ho), a gambler he saved from thugs in Thailand, and by Kim Na Na (Park Min Young), a Blue House bodyguard who finds out his real identity and falls in love with him. Meanwhile, Prosecutor Kim Young Joo (Lee Joon Hyuk), a son of one of the Council of Five, tries to root out corruption in the government while also trying to track and learn the real identity of the City Hunter. Can Yoon Sung succeed or will his heart get in the way of his ability to follow through with his mission? “City Hunter” is a 2011 South Korean drama series directed by Jin Hyuk. It is based on a famous novel by Japanese writer Tsukasa Hojo.", player_url:'http://www.viki.com/player/123881v', number: 2, rating: 'PG', image_url: 'http://0.viki.io/c/73b/8e3/248/city-hunter_590x330.jpg', duration: 3813)
Show.create(name: "Ghost", description: "An elite division of law enforcement goes after criminals who can’t always be seen or found. Kim Woo Hyun (So Ji Sub) is the son of a high-ranking police official who graduated from the police academy at the top of his class. He now works in the cyber investigation department of the police force. But while trying to track down super hacker Park Gi Young (Daniel Choi), Woo Hyun appears to be involved in some shady dealings with some powerful people. When a warehouse accident wipes out two lives, the hacker assumes the identity of Woo Hyun and is determined to investigate what the former Woo Hyun was up to. With the help of fellow cyber-detective Yoo Kang Mi (Lee Yeon Hee), who has an online reputation for being an “uljjang” (good-looking), and geeky Internet expert Jo Hyun Min (Uhm Ki Joon), can the new Woo Hyun discover the truth? “Ghost” is a 2012 South Korean drama series directed by Kim Hyeong Sik.", player_url: 'http://www.viki.com/player/188598v', number: 1, rating: 'PG', image_url: 'http://1.viki.io/c/857/08f/4ea/Ghost_banner_590x330.jpg', duration: 3814)
Show.create(name: "Sex is Zero", description: "Note: Some material might not be appropriate persons under 18. Sex Is Zero (색즉시공, Saekjeuk Shigong) is a 2002 South Korean film written and directed by Yoon Je-kyoon, starring Lim Chang-jung, Ha Ji-won (from ""Secret Garden"") and Yoo Chae-yeong. In the style of American gross-out comedies like American Pie, it follows the exploits of a group of college students, which eventually takes a serious turn. Sex Is Zero sold over 4 million tickets in South Korea, making it the fifth most popular film of 2002.", player_url: 'http://www.viki.com/player/156534v', number: 0, rating: 'M21', image_url: 'http://0.viki.io/c/d7b/8ac/c08/Sex-is-Zero_2.jpg', duration: 5802)
Show.create(name: 'Black Jack', description: "In a world where the grim reaper can strike at any time, a brilliant renegade surgeon known only as Black Jack operates outside the law. For the rich and dying, he performs miracles of a macabre medical nature. Unafraid of mysteries that verge on the paranormal, Black Jack is the one man with the power to cheat death…for a terrible price! In the original story entitled Hurricane. a young wife taking of her rich old husband, who is dying on a solitary island, and his secretary ask Black Jack to prolong the man's life until they can finish altering his will.", player_url: 'http://www.viki.com/player/183964v', number: 1, rating: 'PG', image_url: 'http://1.viki.io/c/5851c/af0c95e374.jpg', duration: 2936)

