# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Show.destroy_all
Show.create(name: "My Princess", description: "Every young girl dreams of becoming a princess when she grows up. But sometimes you have to be careful what you wish for. Lee Seol (Kim Tae Hee) considered herself an average college student, but her world is turned upside down one day when she discovers that she is the descendent of Emperor Sunjong, the last emperor of the Chosun Dynasty. Powerful figures in business and politics are excited by the prospect of restoring the Korean monarchy. The biggest proponent is Park Dong Jae (Lee Soon Jae), president of the Daehan Group, the largest conglomerate in Korea, who pledges to give up his entire fortune to see the Korean monarchy restored. He charges his grandson, Park Hae Young (Song Seung Hun), with the difficult task of preparing Seol to become a princess. The education involves everything from proper etiquette to governmental knowledge, and it’s no easy task. If Hae Young succeeds at making Seol a proper princess, he may lose his inheritance from his grandfather. When Hae Young starts developing feelings for Seol, his motives are put to the test. Oh Yoon Joo (Park Ye Jin), who’s father Oh Ki Taek (Maeng Sang Hoon), works as President Park’s secretary, had her sights set on marrying Hae Young and taking over the company. She will stop at nothing to see the monarchy fail. Can Seol ascend the throne of a Korean monarchy after everything she endures to become a princess? “My Princess” is a 2011 South Korean drama series directed by Kwon Suk Jang.", player_url: '91620v', number: 1, rating: 'PG', image_url: 'http://0.viki.io/c/166/4ac/032/my-princess_590x330.jpg', duration: 3905)
Show.create(name: "Inspiring Generation", description: "Based in the 1930's of Shanghai, China, is a story about love, friendship, patriotism and desire. Shin Jung Tae (Kim Hyun Joong) is an outrageous and clumsy man, but has an unconditional love for his country and family, and was known to be the best fighter in the alleys of Shanghai", player_url: '1028799v', number: 1, rating: 'PG', image_url: 'http://0.viki.io/c/20024c/aa45e461ba.jpg', duration: 3572)
Show.create(name: "Miss Ripley", description: "Two very different men fall in love with Jang Mi Ri, a woman whose life is a complicated web of lies, propelled by her greedy desires that stem from an unfortunate childhood. Jang Myung Hoon is an ambitious hotelier who maintains perfect control of himself and his life, while Yutaka is the warm and gentle heir of a Korean-Japanese hotel conglomerate. Their love for Mi Ri and her tragic ambition eventually lead them down the path of destruction.", player_url: '124587v', number: 1, rating: 'PG', image_url: 'http://1.viki.io/c/ff1/fe4/8ec/miss-ripley_590x330.jpg')
Show.create(name: "Sex is Zero", description: "Note: Some material might not be appropriate persons under 18. Sex Is Zero (색즉시공, Saekjeuk Shigong) is a 2002 South Korean film written and directed by Yoon Je-kyoon, starring Lim Chang-jung, Ha Ji-won (from ""Secret Garden"") and Yoo Chae-yeong. In the style of American gross-out comedies like American Pie, it follows the exploits of a group of college students, which eventually takes a serious turn. Sex Is Zero sold over 4 million tickets in South Korea, making it the fifth most popular film of 2002.", player_url: '156534v', number: 0, rating: 'M21', image_url: 'http://0.viki.io/c/d7b/8ac/c08/Sex-is-Zero_2.jpg', duration: 5802)

